openapi: 3.0.0
info:
  title: Travel API
  description: API documentation for managing trips, orders, and destinations.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/trips:
    get:
      summary: Get all trips
      description: Retrieve a list of all trips.
      responses:
        '200':
          description: A list of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The trip ID
                    name:
                      type: string
                      description: The name of the trip
                    description:
                      type: string
                      description: Details about the trip

    post:
      summary: Create a new trip
      description: Add a new trip to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the trip
                  example: "Adventure to the Alps"
                description:
                  type: string
                  description: Details about the trip
                  example: "A week-long trip to the Alps."
      responses:
        '201':
          description: Trip created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created trip
                  name:
                    type: string
                    description: The name of the trip
                  description:
                    type: string
                    description: The description of the trip
        '400':
          description: Invalid input
  /api/destinations:
    get:
      summary: Get all destinations
      description: Retrieve a list of all destinations.
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The destination ID
                    name:
                      type: string
                      description: The name of the destination
                    country:
                      type: string
                      description: The country of the destination

    post:
      summary: Add a new destination
      description: Create a new destination in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the destination
                  example: "Paris"
                country:
                  type: string
                  description: The country of the destination
                  example: "France"
      responses:
        '201':
          description: Destination created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created destination
                  name:
                    type: string
                    description: The name of the destination
                  country:
                    type: string
                    description: The country of the destination
        '400':
          description: Invalid input
