openapi: 3.0.0
info:
  title: Travel API
  description: API documentation for managing trips, orders, and destinations.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/trips:
    get:
      summary: Get all trips
      description: Retrieve a list of all trips.
      responses:
        '200':
          description: A list of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The trip ID
                    name:
                      type: string
                      description: The name of the trip
                    description:
                      type: string
                      description: Details about the trip
  
  /api/destinations:
    get:
      summary: Get all destinations
      description: Retrieve a list of all destinations.
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The destination ID
                    name:
                      type: string
                      description: The name of the destination
                    country:
                      type: string
                      description: The country of the destination
