openapi: 3.0.0
info:
  title: Travel API
  description: API documentation for managing trips, orders, and destinations.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/trips:
    get:
      summary: Get all trips
      description: Retrieve a list of all trips.
      responses:
        '200':
          description: A list of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The trip ID
                    name:
                      type: string
                      description: The name of the trip
                    description:
                      type: string
                      description: Details about the trip
  /api/orders:
    get:
      summary: Get all orders
      description: Retrieve a list of all orders.
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The order ID
                    tripId:
                      type: integer
                      description: The ID of the associated trip
                    quantity:
                      type: integer
                      description: The quantity of orders
    post:
      summary: Create a new order
      description: Place a new order for a trip.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tripId:
                  type: integer
                  description: The ID of the trip to order
                quantity:
                  type: integer
                  description: The number of items to order
      responses:
        '201':
          description: Order created successfully
  /api/destinations:
    get:
      summary: Get all destinations
      description: Retrieve a list of all destinations.
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The destination ID
                    name:
                      type: string
                      description: The name of the destination
                    country:
                      type: string
                      description: The country of the destination
