openapi: 3.0.0
info:
  title: Travel API
  description: API documentation for managing trips, orders, and destinations.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/trips:
    get:
      summary: Get all trips
      description: Retrieve a list of all trips.
      responses:
        '200':
          description: A list of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The trip ID
                    name:
                      type: string
                      description: The name of the trip
                    description:
                      type: string
                      description: Details about the trip
    post:
      summary: Create a new trip order
      description: Add a new trip booking order to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: string
                  description: Duration of the trip.
                  example: 7 days
                hotel:
                  type: string
                  description: Selected hotel for the trip.
                  example: Deluxe Hotel
                meal:
                  type: string
                  description: Selected meal plan.
                  example: Full board
                transport:
                  type: string
                  description: Selected transport type.
                  example: Private car
                adults:
                  type: integer
                  description: Number of adults.
                  example: 2
                children:
                  type: integer
                  description: Number of children.
                  example: 1
                totalPrice:
                  type: number
                  description: Total price of the trip.
                  example: 1500000
                sumPrice:
                  type: number
                  description: Sum price for all bookings.
                  example: 1800000
                destination:
                  type: string
                  description: Selected destination.
                  example: Хөвсгөл нуур
              required:
                - duration
                - hotel
                - meal
                - transport
                - adults
                - children
                - totalPrice
                - destination
      responses:
        '201':
          description: Trip order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the created trip order.
                  message:
                    type: string
                    description: Success message.
                  data:
                    type: object
                    properties:
                      duration:
                        type: string
                      hotel:
                        type: string
                      meal:
                        type: string
                      transport:
                        type: string
                      adults:
                        type: integer
                      children:
                        type: integer
                      totalPrice:
                        type: number
                      sumPrice:
                        type: number
                      destination:
                        type: string
  /api/destinations:
    get:
      summary: Get all destinations
      description: Retrieve a list of all destinations.
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The destination ID
                    name:
                      type: string
                      description: The name of the destination
                    country:
                      type: string
                      description: The country of the destination