openapi: 3.0.0
info:
  title: Travel API
  description: API documentation for managing trips, orders, and destinations.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Local development server
paths:
  /api/trips:
    get:
      summary: Get all trips
      description: Retrieve a list of all trips.
      responses:
        '200':
          description: A list of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
        '500':
          description: Internal server error
          
    post:
      summary: Create a new trip
      description: Add a new trip to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                  description: The name of the trip
                  example: "Adventure to the Alps"
                  minLength: 3
                  maxLength: 100
                description:
                  type: string
                  description: Details about the trip
                  example: "A week-long trip to the Alps."
                  minLength: 10
                  maxLength: 1000
                startDate:
                  type: string
                  format: date
                  description: Start date of the trip
                  example: "2025-06-01"
                endDate:
                  type: string
                  format: date
                  description: End date of the trip
                  example: "2025-06-08"
      responses:
        '201':
          description: Trip created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/destinations:
    get:
      summary: Get all destinations
      description: Retrieve a list of all destinations.
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        '500':
          description: Internal server error

    post:
      summary: Add a new destination
      description: Create a new destination in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - country
              properties:
                name:
                  type: string
                  description: The name of the destination
                  example: "Paris"
                  minLength: 2
                  maxLength: 50
                country:
                  type: string
                  description: The country of the destination
                  example: "France"
                  minLength: 2
                  maxLength: 50
                description:
                  type: string
                  description: Additional details about the destination
                  example: "The City of Light"
                  maxLength: 500
                coordinates:
                  type: object
                  properties:
                    latitude:
                      type: number
                      format: float
                      minimum: -90
                      maximum: 90
                      example: 48.8566
                    longitude:
                      type: number
                      format: float
                      minimum: -180
                      maximum: 180
                      example: 2.3522
      responses:
        '201':
          description: Destination created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Trip:
      type: object
      properties:
        id:
          type: integer
          description: The trip ID
        name:
          type: string
          description: The name of the trip
        description:
          type: string
          description: Details about the trip
        startDate:
          type: string
          format: date
          description: Start date of the trip
        endDate:
          type: string
          format: date
          description: End date of the trip
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    Destination:
      type: object
      properties:
        id:
          type: integer
          description: The destination ID
        name:
          type: string
          description: The name of the destination
        country:
          type: string
          description: The country of the destination
        description:
          type: string
          description: Additional details about the destination
        coordinates:
          type: object
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        message:
          type: string
          description: Error message
          example: "Invalid input data provided"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: The field that caused the error
              message:
                type: string
                description: Detailed error message for this field